sudo: required
services:
  - docker

before_install:
  - docker build -t iamsirid/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true iamsirid/react-test npm test
after_success:
  - docker build -t iamsirid/multi-client ./client
  - docker build -t iamsirid/multi-nginx ./nginx
  - docker build -t iamsirid/multi-server ./server
  - docker build -t iamsirid/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push iamsirid/multi-client
  - docker push iamsirid/multi-nginx
  - docker push iamsirid/multi-server
  - docker push iamsirid/multi-worker

deploy:
provider: elasticbeanstalk
region: 'ap-southeast-1'
app: 'multi-docker'
env: 'MultiDocker-env'
bucket_name: 'elasticbeanstalk-ap-southeast-1-266417294356'
bucket_path: 'docker-multi'
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
